---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    Bearer:
      description: Bearer user token key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
  schemas:
    user:
      type: object
      properties:
        email:
          type: string
          required: true
        password:
          type: string
          required: true
        organization_attributes:
          type: object
          properties:
            name:
              type: string
              required: true
      example:
        user:
          email: test@test.com
          password: '123456'
          organization_attributes:
            name: test
    user_login:
      type: object
      properties:
        email:
          type: string
          required: true
        password:
          type: string
          required: true
      example:
        user:
          email: test@test.com
          password: '123456'
    device:
      type: object
      properties:
        name:
          type: string
          required: true
        status:
          type: string
          required: true
      example:
        device:
          name: Example Device
          status: 'ON'
    device_port:
      type: object
      properties:
        port:
          type: integer
          required: true
        status:
          type: string
          required: true
      example:
        device_port:
          port: 1
          status: 'ON'
    device_ports:
      type: array
      collectionFormat: multi
      items:
        type: object
        properties:
          port:
            type: integer
            required: true
          status:
            type: string
            required: true
      example:
        device_ports:
        - port: 1
          status: 'ON'
paths:
  "/v1/devices/device_ports":
    post:
      summary: Create device port
      tags:
      - Device ports
      parameters:
      - in: params
        name: locale
        description: Locale
        schema:
          type: string
      security:
      - Bearer: []
      responses:
        '201':
          description: device port created
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/device_ports"
    get:
      summary: Index device ports
      tags:
      - Device ports
      parameters:
      - in: params
        name: locale
        description: Locale
        schema:
          type: string
      security:
      - Bearer: []
      responses:
        '200':
          description: device port index
  "/v1/devices/device_ports/{id}":
    put:
      summary: Update device ports
      tags:
      - Device ports
      parameters:
      - in: params
        name: locale
        description: Locale
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - Bearer: []
      responses:
        '200':
          description: device ports updated
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/device_port"
  "/v1/devices/":
    post:
      summary: Create device
      tags:
      - Devices
      parameters:
      - in: params
        name: locale
        description: Locale
        schema:
          type: string
      security:
      - Bearer: []
      responses:
        '201':
          description: device created
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/device"
    get:
      summary: Index devices
      tags:
      - Devices
      parameters:
      - in: params
        name: locale
        description: Locale
        schema:
          type: string
      security:
      - Bearer: []
      responses:
        '200':
          description: device updated
  "/v1/devices/{id}":
    put:
      summary: Update device
      tags:
      - Devices
      parameters:
      - in: params
        name: locale
        description: Locale
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - Bearer: []
      responses:
        '200':
          description: device updated
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/device"
  "/v1/users/":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '400':
          description: Can't register user
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/user"
  "/v1/users/login":
    post:
      summary: create user session
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Successful login
        '400':
          description: Can't login
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/user_login"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:4000
